### ISSUE TITLE
Setting icon color in tab icon is not working (TabItemHelper.SetIcon)

### ISSUE THREAD

**Issue by Lilium-Candidum** [Kinnara/ModernWpf#115]
Hello,

I used the FontIconEx as shown in #93 and this works well except the icon color. I need the icons in a specific color that matches the icon color shown in the navigation menu.

In the navigation menu, this is the icon:
![image](https://user-images.githubusercontent.com/48719795/84744965-35371d80-afb4-11ea-80a9-1260f7f1f6f2.png)

And this is shown as tab icon:
![image](https://user-images.githubusercontent.com/48719795/84744817-01f48e80-afb4-11ea-81a1-b1c04979eb5c.png)

This is the code:

`              var fontIcon = new FontIconEx
                {
                    Glyph = "\uEA3B",
                    Foreground = new SolidColorBrush((Color)ColorConverter.ConvertFromString("#ff1a1a"))
                };

                TabItemHelper.SetIcon(newTabItem, fontIcon);
`

**Comment by ShankarBUS** [comment]
It works for me?

![image](https://user-images.githubusercontent.com/63704247/84753343-80652680-afdc-11ea-901b-c0cc39180abe.png)

- **XAML**
```xaml
<TabControl>
    <TabItem Content="Edit" Header="Edit">
        <ui:TabItemHelper.Icon>
            <local:FontIconEx Glyph="&#xE104;" Foreground="#ff1a1a"/>
        </ui:TabItemHelper.Icon>
    </TabItem>
    <TabItem Content="Save" Header="Save">
        <ui:TabItemHelper.Icon>
            <local:FontIconEx Glyph="Save" Foreground="#ff1a1a"/>
        </ui:TabItemHelper.Icon>
    </TabItem>
    <TabItem x:Name="newTabItem" Content="Artikel" Header="Artikel"/>
</TabControl>
```
- **Code**
```cs
var fontIcon = new FontIconEx
{
    Glyph = "\uEA3B",
    Foreground = new SolidColorBrush((Color)ColorConverter.ConvertFromString("#ff1a1a"))
};

TabItemHelper.SetIcon(newTabItem, fontIcon);
```
----
# 🤦‍♂️ Why would you use **FontIconEx**?
That is not made by the owner of this repo. Its just an extension over the existing one, made for a user's specific need. **You're not supposed to use it!**. **IT IS NOT OFFICIAL**

#### Try the same with **FontIcon** or **SymbolIcon** to see if they work for you.
- If they do then that must be a specific issue of **FontIconEx** which you shouldn't use
- If they don't then this issue must be updated to contain **FontIcon** instead of **FontIconEx**
