### ISSUE TITLE
NumberBox highlight selection does not extend around arrow parts in Inline mode + others

### ISSUE THREAD

**Issue by geometrikal** [Kinnara/ModernWpf#14]
Found a few more bugs with NumberBox, this time in Inline mode:
- The blue selection highlight ends where the arrows start.
- There is no dividing line between the text and the up arrow
- Missing left and right margin for text or X button
- Arrows part doesn't change with control height

![Annotation 2019-12-16 111146](https://user-images.githubusercontent.com/1187528/70871607-ebfe1500-1ff4-11ea-9c6c-9e19c4046bcb.png)

**Comment by Kinnara** [comment]
Point 1 is more of a design issue than a bug IMO. If it's not critical I think we'll wait until the WinUI version gets improved/fixed.

Points 2 and 3 are mainly caused by the textbox portion not getting enough available width. If you're OK without the X button, the easiest fix/workaround is hiding the button. There's no built-in way to do this but possible with a [helper class](https://gist.github.com/Kinnara/115571105fc318dd9d000a599009a558).

I wasn't able to reproduce Point 4. Could you post the XAML?

**Comment by geometrikal** [comment]
Thanks @Kinnara, looks all good now I've given it enough width, and the blue outline makes more sense:

![Annotation 2019-12-16 233935](https://user-images.githubusercontent.com/1187528/70907764-d2dd7e80-205d-11ea-98fd-b84a4709f48c.png)

As for 4 it was just by setting height = 30 for the xaml in the code, but I will try recreate in a fresh solution to see if it persists there.

XAML:

```xml
<ui:NumberBox Value="{Binding Acquirer.ImageAnalysis.ProcessingConvexityThreshold, Mode=TwoWay}"
                          SpinButtonPlacementMode="Inline"
                          Minimum="0.1"
                          Maximum="1.0"
                          SmallChange="0.05"
                          Header="Min. Convexity"/>
```

**Comment by Kinnara** [comment]
The height of the spin buttons is controlled by the resource `TextControlThemeMinHeight`. Overriding it should make everything size correctly:
```xaml
<ui:NumberBox>
    <ui:NumberBox.Resources>
        <sys:Double x:Key="TextControlThemeMinHeight">50</sys:Double>
    </ui:NumberBox.Resources>
</ui:NumberBox>
```

**Comment by geometrikal** [comment]
Thanks again. I notice that NumberBox doesn't default to TwoWay binding, any idea why they would choose that?

**Comment by Kinnara** [comment]
Because UWP doesn't support defaulting to two-way binding, and I forgot to add it when porting... Anyway I've made `Value` and `Text` bind two-way by default, along with some other properties, via 9a171b8053eb68a7edee38e91ba44451ffe68642. Other properties including `ToggleSwitch.IsOn` and `ToggleSplitButton.IsChecked` already have the correct behavior.
