### ISSUE TITLE
In .NET 5.0 Error

### ISSUE THREAD

**Issue by wf-soft** [Kinnara/ModernWpf#140]
Initialization of 'ModernWpf.ThemeResources' threw an exception.' Line number '10' and line position '18'.

**Comment by ShankarBUS** [comment]
**.NET 5** hmmm, it could be caused due to the WinRT dependency of this library (i.e. to fetch system themes and colors).

One of the **[breaking changes in .NET 5 is the removal of built-in WinRT support](https://github.com/dotnet/runtime/issues/37672)**.
It could be resolved if this library depends on
- **[Microsoft.Windows.SDK.Contracts](https://www.nuget.org/packages/Microsoft.Windows.SDK.Contracts)** nuget package - for **.NET Framework 4.6+** and **.NET Core 3+** and
- **[Microsoft.Windows.SDK.NET](https://www.nuget.org/packages/Microsoft.Windows.SDK.NET)** nuget package - for **.NET 5** (since it doesn't have inbuilt support for WinRT)

This is due to this library having a copy of the metadata files (.winmd files in the [WinMD folder](https://github.com/Kinnara/ModernWpf/tree/master/ModernWpf/WinMD)) instead of depending on the said packages

See this issue for reference - **[Microsoft.Windows.SDK.Contracts - microsoft/CsWinRT/issues/283](https://github.com/microsoft/CsWinRT/issues/283)**

May be IDK 🤷‍♂️. Hey @Kinnara, what are your thoughts?

**Comment by ShankarBUS** [comment]
**⚠⚠ Important ⚠⚠ :**
For **.NET 5**, **using [Microsoft.Windows.SDK.NET](https://www.nuget.org/packages/Microsoft.Windows.SDK.NET) is the _only way_ to consume WinRT APIs**.
But.... there is a problem with it, the **Microsoft.Windows.SDK.NET.dll** is a huge file **(~25 MB)** [will be unpleasant to user 🤦‍♂️]

Hey @wf-soft, I have the fixed the bug in my fork ([ShankarBUS/ModernWpf](https://github.com/ShankarBUS/ModernWpf)) and its working for me. So do this :
- Clone the repository
- Checkout the [dotnet5.0Support](https://github.com/ShankarBUS/ModernWpf/tree/dotnet5.0Support) branch
- Build and run it

Hey @Kinnara,
I can open a PR for this. But... it seems a bit annoying for me to interrupt in your tasks. You're going to do this by yourself anyways and also a PR can't be deleted. So I'm not gonna open a PR this time without your permission.

**Comment by mlivernoche** [comment]
@ShankarBUS I can confirm that your branch has worked. I haven't done extensive testing, but there is no longer any crash on startup.

@Kinnara Here's the stack traces I get when running without these fixes.

The type initializer for 'ModernWpf.ThemeManager' threw an exception.
   at ModernWpf.ThemeManager.get_Current() in ModernWpf\ThemeManager.cs:line 698
   at ModernWpf.ThemeResources.EndInit() in ModernWpf\ThemeResources.cs:line 214
   at ModernWpf.ThemeResources.System.ComponentModel.ISupportInitialize.EndInit() in ModernWpf\ThemeResources.cs:line 238
   at MS.Internal.Xaml.Runtime.ClrObjectRuntime.InitializationGuard(XamlType xamlType, Object obj, Boolean begin)

Inner Exception
The type initializer for 'ModernWpf.ColorsHelper' threw an exception.
   at ModernWpf.ThemeManager..cctor() in ModernWpf\ThemeManager.cs:line 167

Inner Exception
Operation is not supported on this platform. (0x80131539)
   at ModernWpf.ColorsHelper.ListenToSystemColorChanges() in ModernWpf\Helpers\ColorsHelper.cs:line 154
   at ModernWpf.ColorsHelper..ctor() in ModernWpf\Helpers\ColorsHelper.cs:line 34
   at ModernWpf.ColorsHelper..cctor() in ModernWpf\Helpers\ColorsHelper.cs:line 40

**Comment by ShankarBUS** [comment]
Hey @mlivernoche, thanks for the verification. I got the exact same exception before. There won't be any bug anymore since the only problem seemed to be with how .NET 5 interact with WinRT and not within this library. So we can believe nothing wrong will happen 😅. My fix is hard coded for .NET 5, it should modified to include .NET 6, etc when they arrive.

**Comment by wf-soft** [comment]
@ShankarBUS Great. I've been using this library. It's very easy to use

**Comment by Kinnara** [comment]
.NET 5.0 support has been added in the latest preview version. Thank you all for your info and help!

**Comment by ShankarBUS** [comment]
Hey @Kinnara, incase you're not aware the WinRT interop mechanism has been again changed in .NET 5 Preview 8

See https://blogs.windows.com/windowsdeveloper/2020/09/03/calling-windows-apis-in-net5/

**Comment by Kinnara** [comment]
@ShankarBUS Didn't know that. Thanks for the info!

**Comment by ShankarBUS** [comment]
@Kinnara, .NET 5 is expected to be released soon. I hope you'd polish this library for it.

**Comment by Kinnara** [comment]
> @Kinnara, .NET 5 is expected to be released soon. I hope you'd polish this library for it.

Thanks for the reminder, I'll try.

**Comment by Kinnara** [comment]
v0.9.2 should now have proper .NET 5 support (hopefully).

**Comment by jonasnordlund** [comment]
I'm getting this again with the release version of .NET 5 and ModernWpf 0.9.2.

```
TypeInitializationException: The type initializer for 'ModernWpf.ThemeManager' threw an exception.
(Inner Exception) TypeInitializationException: The type initializer for 'ModernWpf.ColorsHelper' threw an exception.
(Inner Exception) System.Windows.Markup.XamlParseException: ''Initialization of 'ModernWpf.ThemeResources' threw an exception.' Line number '9' and line position '18'.'
```

**Comment by ShankarBUS** [comment]
@jonasnordlund,

Is your target framework in this format `net5.0-windows10.0.x.0`. (x is target Windows 10 SDK)?

If not you may get those errors.

**Comment by jonasnordlund** [comment]
@ShankarBUS Thank you, no I didn't set it to the specifik SDK version. Will this make our application require Windows 10 Version 1903? I've chosen this library part because it has pretty low system requirements but this target framework makes me concerned?

**Comment by ShankarBUS** [comment]
No no no, it just means that your app can use APIs from the Windows 10 1903 SDK. It just the SDK you target! Not the minimum supported OS.

This library has internal checks the Windows versions which the app runs to prevent errors on older Windows versions.

It will run on Windows 7 & above with no problems at all! You don't have to worry about anything!
