### ISSUE TITLE
InteropServices.COMException on DwmExtendFrameIntoClientArea

### ISSUE THREAD

**Issue by poochie89** [Kinnara/ModernWpf#144]
A few of my users are reporting the following exception:

```
System.Runtime.InteropServices.COMException: {Desktop composition is disabled} The operation could not be completed because desktop composition is disabled. (Exception from HRESULT: 0x80263001)
at Standard.NativeMethods.DwmExtendFrameIntoClientArea(System.IntPtr hwnd, Standard.MARGINS& pMarInset)
```

Guess it has to do with using "ExtendViewIntoClientArea" on a Window

**Comment by Kinnara** [comment]
`DwmExtendFrameIntoClientArea` is called inside WPF's [WindowChrome class](https://docs.microsoft.com/en-us/dotnet/api/system.windows.shell.windowchrome?view=netcore-3.1). In theory there shouldn't be an exception because the code checks if `DwmIsCompositionEnabled()` before calling it. Might be a graphics adapter driver issue according to [this SO answer](https://stackoverflow.com/a/18003004/3296020).
