### ISSUE TITLE
Settings icon missing from NavigationView on Windows 7

### ISSUE THREAD

**Issue by HadriMX** [Kinnara/ModernWpf#145]
![image](https://user-images.githubusercontent.com/40123110/88354216-7510c380-cd1d-11ea-96a8-264d5b377b62.png)

I already managed to override FontIcon default style to use Segoe MDL2 Assets font (using segmdl2.ttf as a resource), but that doesn't change the NavigationView's settings icon nor the icons used in AppBarButton.
How do I fix that?

**Comment by ShankarBUS** [comment]
Is the Segoe MDL2 Assets font file taken from a latest Windows 10 OS or downloaded from the web.

**Comment by HadriMX** [comment]
Taken from latest Windows 10 version (2004).

**Comment by ShankarBUS** [comment]
Hmm... Interesting. Did you try installing it on the target machine instead of having it as a resource, my apps didn't have this problem. I did this to one of my apps running on Windows 8 and it shows fine.

You replaced the default font family of **FontIcon** only, the settings item could be using a **SymbolIcon**. AFAIK you can't change the font family of SymbolIcon. So the only option is to tell the users to install the font on their system.

**Comment by Kinnara** [comment]
SymbolIcon used to reference the SymbolThemeFontFamily resource, not sure why I decided to hardcode the font. I'll revert the change so that you can override SymbolThemeFontFamily in App.xaml and SymbolIcon will use the overridden value.

**Comment by Kinnara** [comment]
Closed by 58954159d7dee68f10eda79db1a1a2169c60c1bb.
