### ISSUE TITLE
Enable IntelliSense for XAML resources not work

### ISSUE THREAD

**Issue by GF-Huang** [Kinnara/ModernWpf#146]
![image](https://user-images.githubusercontent.com/4510984/88443721-fb2b2800-ce4b-11ea-987b-7d248dbae77d.png)

![image](https://user-images.githubusercontent.com/4510984/88443733-09794400-ce4c-11ea-8a4b-953f673b1135.png)

![image](https://user-images.githubusercontent.com/4510984/88443741-10a05200-ce4c-11ea-9fed-5ba080531c23.png)

![image](https://user-images.githubusercontent.com/4510984/88443746-1a29ba00-ce4c-11ea-8ea6-f54f9c21bb29.png)

Translation:
`error netsdk1022 Duplicate 'Page' items were included. The .NET SDK includes 'Page' items from your project directory by default .....`

**Comment by ShankarBUS** [comment]
Is the IntelliSense not working or the designer for the page not working?

**Comment by GF-Huang** [comment]
If I add `<ItemGroup> <Page>...</Page> </ItemGroup>` into the `*.csproj`, it will cause the project building failure as above `NETSDK1022` error.

If I remove the `<ItemGroup> <Page>...</Page> </ItemGroup>` node from `*.csproj`, it becomes no building errors, but when I typing `<SomeElement someAttribute={StaticResource }>` in VS xaml editor, it does not show any resources such as `SystemControlForegroundBaseMediumBrush` etc..

![image](https://user-images.githubusercontent.com/4510984/88452510-ef625480-ce91-11ea-8577-2d8dd3b5bfa6.png)

**Comment by ShankarBUS** [comment]
Ohhhhh... I got it

The problem is the `DesignTimeResources.xaml` is not a `Page` it is a `ResourceDictionary` **only used by Visual Studio only during Design Time**. You included it as a page and it will be compiled into the source code.

**Follow these steps**
_Step 1 :_ Move the `DesignTimeResources.xaml` file in to **Properties** (create one if not existing) folder (not necessary but this will prevent it from mingling with other xaml files)

Example :
![image](https://user-images.githubusercontent.com/63704247/88452691-7279af80-ce7e-11ea-97a1-822fa14b355f.png)

_Step 2 :_ **Add this in your csproj file instead**

```xaml
  <ItemGroup>
    <Page Remove="Properties\DesignTimeResources.xaml" />
  </ItemGroup>

  <ItemGroup>
    <None Include="Properties\DesignTimeResources.xaml">
      <ContainsDesignTimeResources>True</ContainsDesignTimeResources>
      <SubType>Designer</SubType>
      <Generator>MSBuild:Compile</Generator>
    </None>
  </ItemGroup>
```

**Comment by GF-Huang** [comment]
Great! It works! Thank you!

**Comment by Xinnony** [comment]
Hi,
I follow your fix but same problem.
I find the problem, make sure the file **DesignTimeResources.xaml** is generated as **Resource** and not generated as **Nothing**.

![image](https://user-images.githubusercontent.com/6058403/112720807-edf59a00-8f00-11eb-8943-64e7f52a9138.png)
