### ISSUE TITLE
Integration with FluentWPF (Question)

### ISSUE THREAD

**Issue by kalatchev** [Kinnara/ModernWpf#172]
I am trying to run ModernWpf with FluentWpf. It's wokring, but it isn't what I want to achieve.

When I set `fw:AcrylicWindow.Enabled="True"` on my `Window`, I am getting following result:

![image](https://user-images.githubusercontent.com/10154711/93115836-1c2e2d80-f6c5-11ea-8cfb-a206098ad615.png)

I don't see property like `PaneBackground`, it seems to be fixed gray. How can I have **acrylic background on navigtion view**? And not on Window as it is on the picture?

Thanks in advance!

**Comment by Belim** [comment]
i would just put some frames over the grid and all areas that should not become fluent

**Comment by Kinnara** [comment]
Does [this](https://github.com/Kinnara/ModernWpf/issues/68#issuecomment-616970195) help?

**Comment by Andrew24673** [comment]
> Does [this](https://github.com/Kinnara/ModernWpf/issues/68#issuecomment-616970195) help?

 No, it does not work. I am trying to achieve the result like here: https://github.com/Kinnara/ModernWpf/issues/27
But instead I get a second blur in ContentGrid instead of blurring PaneContentGrid. Replacing ContentGrid with PaneContentGrid in the code didn't help.
I used the code taken from the link above.

`<acrylicControls:AcrylicPanel Target="{Binding ElementName=ContentGrid}" TintOpacity="0.3" TintColor="{DynamicResource SystemChromeMediumColor}" NoiseOpacity="0.025"> <Rectangle Fill="{DynamicResource NavigationViewExpandedPaneBackground}" Opacity="0.2"/> </acrylicControls:AcrylicPanel>`

And so far, it has not been possible to change the NavigationView so that its menu is blurry and transparent.

**Comment by solarkraft** [comment]
Is there really no way to make the background transparent?

**Comment by AlphaNecron** [comment]
Put these below your navigation view in order to enable transparent background
`
            <ui:NavigationView.Resources>
                <SolidColorBrush x:Key="NavigationViewTopPaneBackground" Color="Transparent"/>
                <SolidColorBrush x:Key="NavigationViewDefaultPaneBackground" Color="Transparent"/>
                <SolidColorBrush x:Key="NavigationViewExpandedPaneBackground" Color="Transparent" />
            </ui:NavigationView.Resources>`

**Comment by kalatchev** [comment]
Thank you @AlphaNecron ! It works.
