### ISSUE TITLE
Increasing font size of listbox items not possible

### ISSUE THREAD

**Issue by Belim** [Kinnara/ModernWpf#173]
I find no way to increase and to override the fontsize of the listbox (i guess its 14px by default) also with styles. 
I have also no implicit styles (App.xaml's Resources section etc.) that override my changes.

any idea  what this could be due to?

Many thanks

**Comment by stevemonaco** [comment]
The underlying issue seems to be that the [DefaultListBoxItemStyle](https://github.com/Kinnara/ModernWpf/blob/master/ModernWpf/Styles/ListBox.xaml#L35) binds to `ControlContentThemeFontSize` deeply within a `ControlTemplate`.

There are two workarounds that I know of. The first is to rewrite the style with different bindings for the `FontSize` property, apply the new style to your `ListBox`, and set its `FontSize` in XAML.

`TextElement.FontSize="{TemplateBinding FontSize}"`
Or
`TextElement.FontSize="{Binding RelativeSource={RelativeSource TemplatedParent}, Path=FontSize}"`

The second workaround requires you to replace the `ControlContentThemeFontSize` at the appropriate scope(s), application-level may work for you. There should probably be a `ui:ControlHelper.FontSize` helper for this in the future...

```xml
<StackPanel Orientation="Vertical">
	<Button Content="Test Button" />
	<ListBox ItemsSource="{Binding Items}">
		<ListBox.Resources>
			<sys:Double x:Key="ControlContentThemeFontSize">30</sys:Double>
		</ListBox.Resources>
	</ListBox>
	<Button Content="Test Button" />
</StackPanel>
```

As an aside, replacing the key within `StackPanel.Resources` will change the `FontSize` for both of the `Button`s and the `ListBox`, too.

**Comment by Kinnara** [comment]
This is an issue carried over from the corresponding WinUI style. Another workaround is to specify the ItemTemplate:
```xaml
<ListBox.ItemTemplate>
    <DataTemplate>
        <TextBlock Text="{Binding}" FontSize="20" />
    </DataTemplate>
</ListBox.ItemTemplate>
```

**Comment by Belim** [comment]
The same for the NavigationView. FontSize cant also be increased. Hmm
