### ISSUE TITLE
Future of project with WinUI 3

### ISSUE THREAD

**Issue by nlogozzo** [Kinnara/ModernWpf#181]
Through my understanding .NET 5 and WinUI 3 will bring these modern UWP controls to WPF, similar to this project.
Therefore, what will happen to this project? Are there any benefits/differences to this project vs WinUI 3 with .NET 5?

**Comment by ShankarBUS** [comment]
> Are there any benefits/differences to this project vs WinUI 3 with .NET 5?

- We can use this on any WPF projects running on Windows 7+
- WinUI doesn't support transparent (layered) windows yet. So using this library, I have incorporated **"Fluent Design"** on one of my apps. Without this lib I can't imagine how I would've done it.
- No need for packaging the application to MSIX (WinUI will remove this restriction in the future)
- Can be used together with other WPF UI frameworks simultaneously (WinUI is relatively new and won't have many 3rd party controls and WPF controls can't be used on a WinUI project. But the opposite doesn't apply, we can use any WinUI based libs on a WPF app given that it is either a .NET Core/.NET 5 app using xaml islands)
- WinUI 3+ won't acrylic/reveal until next year. So using this lib or WinUI won't make much of a difference (But I plan to add reveal and acrylic support for this lib in the [ModernWpfCommunityToolkit](https://github.com/ModernWpf-Community/ModernWpfCommunityToolkit))

What else do you need?

> Therefore, what will happen to this project?

What do you think should happen? This project won't be left unmaintained anytime soon. Since many projects depend on this lib, the author should somehow manage to maintain it.

WinUI may seem **"shiny"** and **"opportunistic"** but that wouldn't make it better than WPF.
