### ISSUE TITLE
Extract NavigationView

### ISSUE THREAD

**Issue by ghost1372** [Kinnara/ModernWpf#218]
Hi @ShankarBUS 
I only use the NavigationView control and I do not need any other controls That's why I decided to separate NavigationView control from the ModernWpf, I tried to do this but The result was not interesting and there are problems:
The icon is not displayed
The blue bar next to the item is not displayed
And there may even be other problems, I'm not sure I have a request from you 
Can you please create this control for me in a project?🙏
![Untitled](https://user-images.githubusercontent.com/9213496/101020112-37e9f700-3583-11eb-9114-1eb26723345a.png)

[WpfApp27.zip](https://github.com/Kinnara/ModernWpf/files/5636090/WpfApp27.zip)

**Comment by ShankarBUS** [comment]
There will be many problems decoupling NavigationView from this library due to its dependency on IconElement, ThemeResources, ItemsRepeater and etc.

It's better to keep using this library.

Using a library for a single component is not a bad architecture to be honest. Even though we can make a separate library just for it, it will be a waste of time. Because you may need to change the interface in the future and the decoupled component may be useless then. You can still use this library and not use any controls. It won't cause any performance degradation.

P.S. this is not my repository. Please don't mention me in this repo again.

If you want to contact me in personal, then please contact me in Twitter or mail me.

**Comment by ghost1372** [comment]
I know, but I have other reasons, such as increasing the size of the program Interference with other components.
I also separated these items (IconElement, ThemeResources, ItemsRepeater) Did you see the attached project? and placed them next to the navigation view
The reason I bothered you was because @Kinnara was not very active (The last time it took 15 days to answer a problem) And you have a good knowledge of this library I apologize for this
Anyway, can you help?

**Comment by ShankarBUS** [comment]
Ok I will help you.

**Comment by ghost1372** [comment]
@ShankarBUS  I was finally able to fully extract this control 😁😁
![Untitled](https://user-images.githubusercontent.com/9213496/101768989-8e16e700-3afb-11eb-8abc-8c642fa37a60.png)

**Comment by ShankarBUS** [comment]
Whoa! That's great!

Sorry, I couldn't find time to help you.

I'm happy that you've done it yourself.

**Comment by ghost1372** [comment]
> Whoa! That's great!
> 
> Sorry, I couldn't find time to help you.
> 
> I'm happy that you've done it yourself.

thank you ❤ It took a while but I was able to understand the structure of the project i event extracted more controls and styles😁
Just one more thing I do not have information about WinRT. Are its classes open source? I want to extract UISettings class that used in ColorsHelper class

**Comment by ShankarBUS** [comment]
@ghost1372,

> Just one more thing I do not have information about WinRT. Are its classes open source? I want to extract UISettings class that used in ColorsHelper class

Unfortunately those are built-in OS APIs.

WinRT API can still be consumed by any .NET Windows apps (given that you careful catch exceptions and call OS specific only on the minimum supported OSes).

Reference:

https://blogs.windows.com/windowsdeveloper/2020/09/03/calling-windows-apis-in-net5/

https://blogs.windows.com/windowsdeveloper/2019/09/30/windows-10-winrt-api-packs-released/
