### ISSUE TITLE
ContentDialog Visibility?

### ISSUE THREAD

**Issue by edulf1998** [Kinnara/ModernWpf#26]
Hi! I'm doing a project for school right now using this library. It's been working as expected and it's really useful, but I can't seem to get ContentDialog to show.

My app uses MVVM, and in the viewmodel I have the following boolean property:
`public bool ShowDialog { get; set; }`

In the XAML I define a ContentDialog and bind its Visibility property to the property above (I've also tried using the BooleanToVisibilityConverter for this step). This doesn't seem to work, though. 

Am I doing something wrong? Or is it the fact that I'm using the ContentDialog as-is and I need to define it in a separate class for this to work?

**Comment by Kinnara** [comment]
Please refer to [Dialog controls](https://docs.microsoft.com/en-us/windows/uwp/design/controls-and-patterns/dialogs-and-flyouts/dialogs) on how to use ContentDialog. It's for the UWP ContentDialog but the API is almost identical.

**Comment by ShankarBUS** [comment]
Changing the ContentDialog's Visibility is not that useful. It has a method **ShowAsync** method which is the problem here I guess 🤷‍♂️. You are trying to alter the visibility of a control which is not even shown, that's why you have this issue I guess. I did what I can to solve this.

Check my code (don't forget to update the project reference to ModernWpf library into nuget reference)
[ContentDialogMVVMTest.zip](https://github.com/Kinnara/ModernWpf/files/4293109/ContentDialogMVVMTest.zip)

This is the VM (the content dialog is in a seperate file and not in the main window, I used the example from ModernWpf.SampleApp. Therefore you can modify the template in **ContentDialogExample.xaml**)

```cs
using System.ComponentModel;
using System.Runtime.CompilerServices;

namespace ContentDialogMVVMTest
{
    public class MyViewModel : INotifyPropertyChanged
    {
        // This is only way to do it in MVVM since ContentDialog has to be shown using a method
        private ContentDialogExample dialog = new ContentDialogExample(); 

        private bool showDialog = false;

        public bool ShowDialog
        {
            get { return showDialog; }
            set
            {
                if (!value == showDialog) { showDialog = value; ShowDialogChanged(value); OnPropertyChanged();}
            }
        }

        private async void ShowDialogChanged(bool value)
        {
            if (value) 
            {
                var result = await dialog.ShowAsync();
                // Do your work here
                ShowDialog = false;// This is only to update the Binding
            }
            else 
            {
                dialog.Hide();
            }
        }

        public event PropertyChangedEventHandler PropertyChanged;
        protected void OnPropertyChanged([CallerMemberName] string propertyName = "")
        {
            if (PropertyChanged != null)
            {
                PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
            }
        }
    }
}
```

If you're issue is resolved then **Close** this issue

**Comment by ShankarBUS** [comment]
> In the XAML I define a ContentDialog and bind its Visibility property to the property above (I've also tried using the BooleanToVisibilityConverter for this step). This doesn't seem to work, though.

Since you have to show that dialog using ShowAsync method because a dialog has to return a result.
> Am I doing something wrong? Or is it the fact that I'm using the ContentDialog as-is and I need to define it in a separate class for this to work?

Yes in a **MVVM** project you shouldn't have codes in **CodeBehind** of the **View**.
But for a dialog which is defined in the **View** to show and return a result you have control it from the **View** (Which is against **MVVM**).
Thus you have define the dialog in a seperate file (a new .xaml file [like a user control], So that you will be able to modify its template, which you can't do in the VM). Create and store a instance of the dialog in the VM (thats what I did above) and control it from there. It will work hella fine 👌
