### ISSUE TITLE
TransitionFrame - the position of previous pages

### ISSUE THREAD

**Issue by ORRNY66** [Kinnara/ModernWpf#37]
Hi,
I noticed that the frame in HamburgerMenu does not show the previous pages with the saved position (see picture). For example, in Groove music it is common to display previous pages with a saved position, see gif

![gif06](https://user-images.githubusercontent.com/5471789/74687502-d6fc5880-51d4-11ea-9c31-a977ee2795e4.gif)

![gif07](https://user-images.githubusercontent.com/5471789/74687530-f1cecd00-51d4-11ea-9cce-a3cc3d5ceee4.gif)

**Comment by ShankarBUS** [comment]
Same can be observed in **Xaml Controls Gallery**. It's up-to the developer whether to **re-create navigation pages** every time the user navigates (i.e. pages are dynamically created using their **Type**) and **detach the old pages** which causes the **ScrollViewer** to be created fresh, losing the previous scroll position 

Instead of passing a **Type** as argument like **Frame.Navigate(Type)**, if a **Page** is passed as argument like **Frame.Navigate(Page)** the page **won't be re-created** it will be just loaded having **all previous properties and states**.

### Thus this not really a issue for this library. It's the devs preference.
### There is nothing to do with **HamburgerMenuEx** or the new **NavigationView**. It's the devs preference.

**Comment by ShankarBUS** [comment]
Hey @Kinnara, can this issue be closed?

**Comment by Kinnara** [comment]
Yes, as it's not really specific to this library.
