### ISSUE TITLE
Combobox Creating new Template

### ISSUE THREAD

**Issue by vlknd** [Kinnara/ModernWpf#66]
Dont know if its a bug, or my fault... 

if i create a new copy of  a template for a combobox, i get following error, when running my application:

there is no useable namespace for resolving "Shdw"??

original error msg in german:

System.InvalidOperationException: "Es ist kein verwendbarer Namensbereich zum Auflösen des Namens "Shdw" vorhanden."

but if i follow the same procedure with a button for e.g. it works without any problem...

im new into coding, with visual studio 2019... if thats necessary.. 

since there is no possibility to private message you, kinnara, i had to "misuse" this issue feature...

keep up the good work!

**Comment by vlknd** [comment]
just for clarification.. all i want to do is, to set a different mouse-over color for these controls.. 
as i said before, with a buttton, it was easy. but for combobox it wont work so easy this way..

**Comment by Kinnara** [comment]
It's probably a bug that has been fixed in [the latest preview version](https://www.nuget.org/packages/ModernWpfUI/0.8.3-preview.200417.3). Give it a try if you haven't already.

Changing the mouse-over color usually doesn't require re-templating thanks to [Lightweight styling](https://docs.microsoft.com/en-us/windows/uwp/design/controls-and-patterns/xaml-styles#lightweight-styling). See [the UWP ComboBox page](https://docs.microsoft.com/en-us/uwp/api/Windows.UI.Xaml.Controls.ComboBox?view=winrt-18362#control-style-and-template) for a list of resources you can override. For example, to change the background color on hover, your `ui:ThemeResources` element in App.xaml would look like this:
```xaml
<ui:ThemeResources>
    <ui:ThemeResources.ThemeDictionaries>
        <ResourceDictionary x:Key="Light" ui:ThemeDictionary.Key="Light">
            <SolidColorBrush x:Key="ComboBoxBackgroundPointerOver" Color="Red" />
        </ResourceDictionary>
        <ResourceDictionary x:Key="Dark" ui:ThemeDictionary.Key="Dark">
            <SolidColorBrush x:Key="ComboBoxBackgroundPointerOver" Color="Green" />
        </ResourceDictionary>
    </ui:ThemeResources.ThemeDictionaries>
</ui:ThemeResources>
```

You can also ask questions on [gitter](https://gitter.im/ModernWpf/community?utm_source=share-link&utm_medium=link&utm_campaign=share-link).
