### ISSUE TITLE
Licensing

### ISSUE THREAD

**Issue by spasas** [Kinnara/ModernWpf#70]
Hi,

We would like to use your project in our application, but the legal team has blocked it because of some dependency licenses. 

Those dependencies are:
- Shipwreck.Phash.Bitmaps (GNU GENERAL PUBLIC LICENSE v3)
- SonarAnalyzer.CSharp (GNU LESSER GENERAL PUBLIC LICENSE v3)
- itext7 (GNU Affero General Public License v3+)

Here is the path to those dependencies:
ModernWPF > (MahApps) MahApps.Metro/src/MahApps.Metro.Samples/MahApps.Metro.Caliburn.Demo > (FODY) FodyHelpers.Tests.csproj > Verify.Xunit > Shipwreck.Phash.Bitmaps
ModernWPF > (MahApps) MahApps.Metro/src/MahApps.Metro.Samples/MahApps.Metro.Caliburn.Demo > (COSTURA.FODY) Costura/src/Costura.Fody.Tests > ApprovalTests > itext7
ModernWPF > (MahApps) MahApps.Metro/src/MahApps.Metro.Samples/MahApps.Metro.Caliburn.Demo > (COSTURA.FODY) Costura/src/Costura.Fody.IntegrationTests > TomsToolbox.Wpf > WeakEventHandler.Fody > SonarAnalyzer.CSharp

The dependencies are not directly used but the ModernWpf project per se, but there is a link. Legal asks us to follow the whole path. As it turns out, we do not need the MahApps extension, but we cannot clone/fork the repo locally because it would download those dependencies on our system. Legal prefers not to have any trace of this project locally. Thus, we cannot clone/fork it locally and not use it nor delete it.

It is possible to provide your project without the MahApps extension ? Could you extract MahApps and put it on another repo ? Can we help ? We really want to use your project and still be able to update as often as you push new features. In the end, we still have a workaround if you cancel this issue.

Thanks for your time and this project.

**Comment by andrew-boyarshin** [comment]
I am neither speaking for ModernWPF project, nor knowledgeable in legal terms, but are these paths relevant? They _are_ in MahApps repo, but to use or modify ModernWPF you needn't clone MahApps repo (unless you need to modify MahApps). Instead, you consume project primary binaries, which don't contain/use the code in question (these are in samples, after all), hence, none of the GPL/LGPL/AGPL-licensed code, neither in source nor binary form, is downloaded on your system.

**Comment by spasas** [comment]
@andrew-boyarshin I think you are right. But before getting back with legal, we wanted to know if it could be possible to remove MahApps from the project. Just to know if it is a possibility.

**Comment by spasas** [comment]
We've talked about it yesterday and we accept @andrew-boyarshin answer. No need to split the project thus closing the issue.

**Comment by alkbed** [comment]
Hi,

In the previous messages of this issue, we saw that the mentioned dependencies were in fact not relevant to our case. However, the legal team blocked us for another licensing issue.

The MIT licensing is permissive and allows us to use the project for our application. However, ModernWpf contains files that have the MS-PL licensing, which is more restrictive than the MIT licensing. 

We understand both licenses are permissive in the sense that they allow us to use and distribute any derivative work done on projects using them, as long as we comply with their conditions and limitations. However, our legal department wishes that we do not use projects using the MS-PL license since it would be impossible for us to comply with it.

Here is a list of files in this project that use the MS-PL licensing:
1.  ModernWpf/Transitions/Storyboards/SlideLeftln.xaml
2.  ModernWpf/Transitions/Storyboards/SlideRightln.xaml
3.  ModernWpf/Transitions/Storyboards/SlideUp.xaml
4.  ModernWpf/Transitions/Storyboards/SlideDown.xaml
5.  ModernWpf/Transitions/Storyboards/SlideLeftOut.xaml
6.  ModernWpf/Transitions/Storyboards/SlideRightOut.xaml
7.  ModernWpf/Transitions/TransitionElement.cs
8.  ModernWpf/Transitions/Transitions/SlideTransitionMode.cs
9.  ModernWpf/Transitions/Transitions/SlideTransition.cs
10. ModernWpf/Transitions/ITransition.cs
11. ModernWpf/Transitions/NavigationTransition.cs
12. ModernWpf/Transitions/Transitions.cs
13. ModernWpf/Transitions/TransitionService.cs
14. ModernWpf/Transitions/Transitions/Transition.cs
15. ModernWpf/Transitions/TransitionFrame.cs
16. ModernWpf/Navigation/Frame.cs

My questions are the following: What was the rationale behind using MIT as a primary licensing and not MS-PL, and could it be possible for you to remove the use of this license in your project?

Thank you for your time and insights on this issue. Also, thank you for your work on this project.

**Comment by spasas** [comment]
I reopen to follow up on @alkbed update.

**Comment by Kinnara** [comment]
The reason there are some MS-PL licensed files is they were ported from the Windows Phone Toolkit and I wasn’t aware of the incompatibility between the licenses. After a bit of research, I believe the simplest solution would be removing these files (they have been deprecated anyway, although still used internally) and reimplementing the page transition feature. Hopefully this can be done within a week.
