### ISSUE TITLE
(Feature Request) Button Reveal Styles

### ISSUE THREAD

**Issue by nlogozzo** [Kinnara/ModernWpf#77]
Hi All,
I would like to request button reveal styles similar to FluentWPF. I would use FluentWPF, however I like to rely on as few libraries as possible and don't want any conflicts to occur between the libraries.
Thanks in advanced

**Comment by ShankarBUS** [comment]
FluentWpf uses **MarkupExtensions** for reveal, would be better if it can be defined in a resource.

**Comment by nlogozzo** [comment]
Additionally this would be nice as using the reveal style from FluentWPF completely overrides the ModernWPF's button style, making it button look out of place from the rest of ModernWPF controls. Therefore, adding a reveal style to the ModernWPF's button style would be nice.

**Comment by ShankarBUS** [comment]
@Kinnara,

I have successfully implemented reveal effect in one of my apps.
https://github.com/ModernFlyouts-Community/ModernFlyouts/tree/main/ModernFlyouts/UI/Fluent/Media

This implementation is in line with **ModernWpf** and **WinUI**.
The styles would respect all aspects of **ModernWpf** (such as CornerRadius, FocusVisual, Theming & etc.)

I'm planning to move them to our toolkit so that others can be benefitted too.

But due to #126,
I have to make my own workaround for theming support.
https://github.com/ModernFlyouts-Community/ModernFlyouts/tree/main/ModernFlyouts/ThemeResources

This leads to a problem. i.e. I have to keep a copy of several resources present in here
https://github.com/ModernFlyouts-Community/ModernFlyouts/blob/bff841fc31b0fcdd791c9daa5fdb05be11cc57a9/ModernFlyouts/ThemeResources/Dark/RevealBrush.xaml#L19-L25

So, I thought it would be great if we can settle down and add this directly to **ModernWpf**.
There are no other external dependencies. Just some helpers and styles.

What do you think?

**Comment by ShankarBUS** [comment]
By doing so, we can also provide native support for reveal effect in **NavigationView**, **AppBarButton** and etc.

And also, if you give me the permission, I can make a PR for **in-app acrylic effect**.
Please consider my offer.

**Comment by nlogozzo** [comment]
Status on this PR? I would like to have button reveal styles as well as in-app acrylic without the need of FluentWPF
