### ISSUE TITLE
How to get a system theme with ThemeManager?

### ISSUE THREAD

**Issue by denik7770** [Kinnara/ModernWpf#9]
`tbsys.Text = ModernWpf.ThemeManager.GetActualTheme(this).ToString();`
This does not return me an actual theme, it returns a requested theme, but if there isno requested theme, then it returns default.

**Comment by denik7770** [comment]
![sssss](https://user-images.githubusercontent.com/47399010/69271573-ecd49000-0b89-11ea-8f63-f8c4e968b899.png)

**Comment by Kinnara** [comment]
In theory, your code should work and `GetActualTheme` should always return either `Light` or `Dark` but never `Default`, otherwise there is a bug. Anyway, what it returns doesn't matter much unless you're using more advanced features like defining/overriding theme resources at the element level.

Without seeing the code it can be hard to tell what exactly went wrong in your case. One issue I see is that both ModernWPF and FluentWPF are trying to set the window style (through attached property) and only one will take effect. For the moment I believe using the FluentWPF style would be simpler. The resources in App.xaml also need to be set up in a certain way to get the two libraries work together without conflicts. I made a sample app [available here](https://github.com/Kinnara/ModernWpf/tree/master/samples/FluentWPFSample) to demonstrate the setup.

![image](https://user-images.githubusercontent.com/1617766/69349338-88f9b680-0cb2-11ea-9181-f34014dbfb92.png)

**Comment by denik7770** [comment]
Thank you reaally much for your answer and support!!😊😊

**Comment by ashelleyPurdue** [comment]
Slightly off topic, but what would be the purpose behind using both FluentWPF and ModernWpf?  I thought ModernWpf was, more or less, a replacement for FluentWPF.

Is it so your app can make use of the acrylic effect?

**Comment by denik7770** [comment]
I think, that to make an acrylic effect, the best way is by using FluentWPF.

**Comment by denik7770** [comment]
> In theory, your code should work and `GetActualTheme` should always return either `Light` or `Dark` but never `Default`, otherwise there is a bug. Anyway, what it returns doesn't matter much unless you're using more advanced features like defining/overriding theme resources at the element level.
> 
> Without seeing the code it can be hard to tell what exactly went wrong in your case. One issue I see is that both ModernWPF and FluentWPF are trying to set the window style (through attached property) and only one will take effect. For the moment I believe using the FluentWPF style would be simpler. The resources in App.xaml also need to be set up in a certain way to get the two libraries work together without conflicts. I made a sample app [available here](https://github.com/Kinnara/ModernWpf/tree/master/samples/FluentWPFSample) to demonstrate the setup.
> 
> ![image](https://user-images.githubusercontent.com/1617766/69349338-88f9b680-0cb2-11ea-9181-f34014dbfb92.png)

I'm still getting this issue, but at least, they do not conflict with themes.
![Untitleaad](https://user-images.githubusercontent.com/47399010/69368715-7ac67e80-0c4f-11ea-8fb4-4a5c883eaab9.png)

**Comment by Kinnara** [comment]
Ah, now I see you want the app to use the Windows theme mode. Simply adding a proper app manifest should enable that. This commit 84f40691bb33fa02b2450fe246858a3b7d1e8b80 shows how to do that. Basically you add an app manifest to your project and uncomment the Windows 10 line.

If your app still doesn't pick up the Windows theme (don't forget to remove any `RequestedTheme`) I also made some changes that should make system theme handling more robust. It's not published on NuGet yet but you can clone the latest code and try the FluentWPF sample.

![image](https://user-images.githubusercontent.com/1617766/69438538-2d95fa00-0d80-11ea-9aa1-87f724acd1bd.png)

**Comment by ShankarBUS** [comment]
Hey @Kinnara, Since the requirement for app.manifest is now optional, apps will now follows system themes without any additional requirements.

The OP's problem was, they couldn't fetch system theme because they didn't have the manifest and didn't know it was required.

Can this issue be closed now?

**Comment by Kinnara** [comment]
Yes, I believe so. Thanks for the reminder.
